export const productData = {
  header: [
    "№",
    "Наименование",
    "Код",
    "Баркод",
    "Кол-во",
    "Ряд",
    "Стеллаж",
    "Полка",
    "Сотрудник",
  ],
  body: [
    {
      id: "1",
      name: "Творог 15% Наманган",
      code: "654818",
      barcode: "4698498642187",
      quantity: "328",
      row: "5",
      rack: "A",
      shelf: "VII",
      employee: "Муроджон Турсунов",
    },
    {
      id: "2",
      name: "Творог 15% Наманган",
      code: "654818",
      barcode: "4698498642187",
      quantity: "328",
      row: "5",
      rack: "A",
      shelf: "VII",
      employee: "Муроджон Турсунов",
    },
    {
      id: "2",
      name: "Творог 15% Наманган",
      code: "654818",
      barcode: "4698498642187",
      quantity: "328",
      row: "5",
      rack: "A",
      shelf: "VII",
      employee: "Муроджон Турсунов",
    },
    {
      id: "2",
      name: "Творог 15% Наманган",
      code: "654818",
      barcode: "4698498642187",
      quantity: "328",
      row: "5",
      rack: "A",
      shelf: "VII",
      employee: "Муроджон Турсунов",
    },
    {
      id: "2",
      name: "Творог 15% Наманган",
      code: "654818",
      barcode: "4698498642187",
      quantity: "328",
      row: "5",
      rack: "A",
      shelf: "VII",
      employee: "Муроджон Турсунов",
    },
  ],
  order: [
    "id",
    "name",
    "code",
    "barcode",
    "quantity",
    "row",
    "rack",
    "shelf",
    "employee",
  ],
};
